# Generated by Django 3.1 on 2021-04-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasbinRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ptype', models.CharField(max_length=255, verbose_name='权限类型')),
                ('v0', models.CharField(max_length=255, verbose_name='角色')),
                ('v1', models.CharField(max_length=255, verbose_name='请求路径')),
                ('v2', models.CharField(blank=True, max_length=255, null=True, verbose_name='请求方法')),
                ('v3', models.CharField(blank=True, max_length=255, null=True)),
                ('v4', models.CharField(blank=True, max_length=255, null=True)),
                ('v5', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'casbin_rule',
            },
        ),
    ]
